equirectangular_node:
  ros__parameters:
    name: insta360_air
    cx_offset: 0.0
    cy_offset: 0.0
    crop_size: 731
    translation: [0.006, 0.01, -0.249]
    rotation_deg: [0.0, 0.0, 0.0]
    gpu: True
    out_width: 1920
    out_height: 960
    